name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Setup nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
          echo 'export NVM_DIR="$HOME/.nvm"' >> $HOME/.bashrc
          echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $HOME/.bashrc
          echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> $HOME/.bashrc

      - name: Install Node.js
        run: |
          source $HOME/.bashrc
          nvm install --lts
          nvm use --lts

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Deploy
        env:
          GIT_USER: ${{ secrets.GITHUB_TOKEN }}
        run: USE_SSH=false npm run deploy